  name: titanic_env
  channels:
    - defaults
    - conda-forge
  dependencies:
    - python=3.10
    - scikit-learn
    - pandas
    - numpy
    - mlflow
    - dagshub
    - joblib
    - pip
    - pip:
        - boto3
