name: titanic_env_ci
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - scikit-learn
  - pandas
  - numpy
  - joblib
  - pip
  - pip:
      - mlflow
      - dagshub
      - boto3
