name: MLflow CI Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: randomforest_env
          environment-file: MLProject/conda.yaml
          python-version: 3.10
          auto-activate-base: false

      - name: Install MLflow
        run: |
          pip install mlflow dagshub

      - name: Run MLflow Project (Training)
        run: |
          mlflow run MLProject -P data_path=titanicdataset_preprocessing/train_preprocessed.csv

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: MLProject/random_forest_basic.pkl

      - name: Build Docker image with MLflow
        run: |
          mlflow models build-docker -m MLProject/random_forest_basic.pkl -n randomforest_ci

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag randomforest_ci ${{ secrets.DOCKERHUB_USERNAME }}/randomforest_ci:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/randomforest_ci:latest
